### ISSUE TITLE
BroadcastTxError: Broadcasting transaction failed with code 13 

### ISSUE THREAD

**Issue by md-rifatkhan** [We-Bump/Lighthouse-cli#10]
Getting error for lighthouse deploy

```
Deploying CW721 ContractC:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\cosmwasmclient.js:189
            return Promise.reject(new stargate_1.BroadcastTxError(broadcasted.code, broadcasted.codespace ?? "", broadcasted.log));
                                  ^

BroadcastTxError: Broadcasting transaction failed with code 13 (codespace: sdk). Log: 
    at SigningCosmWasmClient.broadcastTx (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\cosmwasmclient.js:189:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SigningCosmWasmClient.upload (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:93:24) {
  code: 13,
  codespace: 'sdk',
  log: ''
}

```

**Comment by md-rifatkhan** [comment]
config.json: ```
{
    "mnemonic": "Secured",
    "rpc": "https://sei-t.rpc.n0ok.net",
    "network": "atlantic-2",
    "name": "Meta",
    "symbol": "MT",
    "description": "Meta Coming hahaha",
    "supply": 10,
    "token_uri": "my url",
    "royalty_percent": 5,
    "royalty_wallet": "sei1rmrm79xyjmcv0lt096x8pj5d7h2k0vpjlt4f3m",
    "iterated_uri": true,
    "start_order": 1,
    "frozen": false,
    "hidden_metadata": false,
    "placeholder_token_uri": null,
    "groups":  [  
        {  
        "name":  "whitelist",  
        "merkle_root":  "my merkle_root",  
        "max_tokens":  3,  
        "unit_price":  0.05,  
        "start_time":  "2023-06-02T11:00:00Z",  
        "end_time":  "2023-06-03T11:50:00Z"  
        },  
        {  
        "name":  "public",  
        "merkle_root":  null,  
        "max_tokens":  5,  
        "unit_price":  0.1,  
        "start_time":  "2023-06-02T11:50:25Z",  
        "end_time":  null  
        }  
        ]
}
```

**Comment by md-rifatkhan** [comment]
Config JSON : ```
{
    "mnemonic": "Secured",
    "rpc": "https://sei-t.rpc.n0ok.net",
    "network": "atlantic-2",
    "name": "Meta",
    "symbol": "MT",
    "description": "Meta Coming hahaha",
    "supply": 10,
    "token_uri": "my url",
    "royalty_percent": 5,
    "royalty_wallet": "sei1rmrm79xyjmcv0lt096x8pj5d7h2k0vpjlt4f3m",
    "iterated_uri": true,
    "start_order": 1,
    "frozen": false,
    "hidden_metadata": false,
    "placeholder_token_uri": null,
    "groups":  [  
        {  
        "name":  "whitelist",  
        "merkle_root":  "my merkle_root",  
        "max_tokens":  3,  
        "unit_price":  0.05,  
        "start_time":  "2023-06-02T11:00:00Z",  
        "end_time":  "2023-06-03T11:50:00Z"  
        },  
        {  
        "name":  "public",  
        "merkle_root":  null,  
        "max_tokens":  5,  
        "unit_price":  0.1,  
        "start_time":  "2023-06-02T11:50:25Z",  
        "end_time":  null  
        }  
        ]
}


```

**Comment by md-rifatkhan** [comment]
Tried with` lighthouse deploy --code 865`

Got : ```
Using existing CW721 contract with code ID: 865
⠋ Registering CollectionC:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\queryclient\queryclient.js:134
            throw new Error(`Query failed with (${response.code}): ${response.log}`);
                  ^

Error: Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: Error parsing into type lighthouse::msg::ExecuteMsg: Expected this character to be either a `','` or a `'}'`.: execute wasm contract failed [sei-protocol/sei-wasmd@v0.0.4/x/wasm/keeper/keeper.go:364] With gas wanted: '10000000' and gas used: '140157' : unknown request
    at QueryClient.queryAbci (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\queryclient\queryclient.js:134:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.request (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\queryclient\utils.js:35:30)
    at async Object.simulate (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\modules\tx\queries.js:48:34)
    at async SigningCosmWasmClient.simulate (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:79:29)
    at async SigningCosmWasmClient.signAndBroadcast (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:285:35)
    at async SigningCosmWasmClient.executeMultiple (C:\Users\user\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:228:24)

Node.js v18.18.0
```
