### ISSUE TITLE
lighthouse deploy error

### ISSUE THREAD

**Issue by BrainAxe88** [We-Bump/Lighthouse-cli#14]
HI guys I when I deploy the lighthouse I get the error code below, May I know what is the error here?

Registering CollectionC:\Users\User\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\queryclient\queryclient.js:134
            throw new Error(`Query failed with (${response.code}): ${response.log}`);
                  ^

Error: Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: Share percentage sum must equal to 100: execute wasm contract failed [sei-protocol/sei-wasmd@v0.0.4/x/wasm/keeper/keeper.go:364] With gas wanted: '10000000' and gas used: '135444' : unknown request
    at QueryClient.queryAbci (C:\Users\User\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\queryclient\queryclient.js:134:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.request (C:\Users\User\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\queryclient\utils.js:35:30)
    at async Object.simulate (C:\Users\User\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\stargate\build\modules\tx\queries.js:48:34)
    at async SigningCosmWasmClient.simulate (C:\Users\User\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:79:29)
    at async SigningCosmWasmClient.signAndBroadcast (C:\Users\User\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:285:35)
    at async SigningCosmWasmClient.executeMultiple (C:\Users\User\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:228:24)

Node.js v20.11.0

**Comment by sirhercules** [comment]
make sure all creators share sum is 100
```
 "creators": [
          {
              "address": "creator-wallet-address",
              "share": 100
          }
      ],
 ```
