### ISSUE TITLE
Headers Error

### ISSUE THREAD

**Issue by ibn5x** [We-Bump/Lighthouse-cli#18]
Im getting the following error when attempting to upload images and metadata to arweave:

C:\Users\IBN5X\AppData\Roaming\nvm\v16.13.0\node_modules\@we-bump\lighthouse-cli\node_modules\arweave\node\lib\api.js:46
        const headers = new Headers(init?.headers || {});
                        ^

ReferenceError: Headers is not defined
    at Api.request (C:\Users\IBN5X\AppData\Roaming\nvm\v16.13.0\node_modules\@we-bump\lighthouse-cli\node_modules\arweave\node\lib\api.js:46:25)
    at Api.get (C:\Users\IBN5X\AppData\Roaming\nvm\v16.13.0\node_modules\@we-bump\lighthouse-cli\node_modules\arweave\node\lib\api.js:30:27)
    at Transactions.getPrice (C:\Users\IBN5X\AppData\Roaming\nvm\v16.13.0\node_modules\@we-bump\lighthouse-cli\node_modules\arweave\node\transactions.js:54:36)
    at C:\Users\IBN5X\AppData\Roaming\nvm\v16.13.0\node_modules\@we-bump\lighthouse-cli\arweave.js:269:43
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\IBN5X\AppData\Roaming\nvm\v16.13.0\node_modules\@we-bump\lighthouse-cli\arweave.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ibn5x** [comment]
problem was solved by using current version of node
