### ISSUE TITLE
lighthouse deploy error

### ISSUE THREAD

**Issue by codeReturn** [We-Bump/Lighthouse-cli#6]
Hello guys,
PS E:\Projects\sei-mint-update> lighthouse deploy
⠹ Deploying CW721 ContractC:\Users\PC\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\cosmwasmclient.js:84
            throw new Error(`Account '${address}' does not exist on chain. Send some tokens there before trying to query sequence.`);
                  ^

Error: Account 'sei13syey3es73nj4e0r54fggq3nm9y7meqgpfnssq' does not exist on chain. Send some tokens there before trying to query sequence.
    at SigningCosmWasmClient.getSequence (C:\Users\PC\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\cosmwasmclient.js:84:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SigningCosmWasmClient.simulate (C:\Users\PC\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:78:30)
    at async SigningCosmWasmClient.signAndBroadcast (C:\Users\PC\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:285:35)       
    at async SigningCosmWasmClient.upload (C:\Users\PC\AppData\Roaming\npm\node_modules\@we-bump\lighthouse-cli\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:93:24)

The problem is that this address dont exist in my code sei13syey3es73nj4e0r54fggq3nm9y7meqgpfnssq

**Comment by victorbuttner** [comment]
To solve it you should send some SEI to the address.
