### ISSUE TITLE
Error Registering Collection 

### ISSUE THREAD

**Issue by victorbuttner** [We-Bump/Lighthouse-cli#9]
Hi,

I'm trying to register a collection on testnet and when run the command deploy got this error:

⠋ Registering Collection/Users/victorbuttner/.nvm/versions/node/v19.8.1/lib/node_modules/@we-bump/lighthouse-cli/node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:134
            throw new Error(`Query failed with (${response.code}): ${response.log}`);
                  ^

Error: Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: Error parsing into type lighthouse::msg::ExecuteMsg: Invalid type: execute wasm contract failed [sei-protocol/sei-wasmd@v0.0.4/x/wasm/keeper/keeper.go:364] With gas wanted: '10000000' and gas used: '134540' : unknown request
    at QueryClient.queryAbci (/Users/victorbuttner/.nvm/versions/node/v19.8.1/lib/node_modules/@we-bump/lighthouse-cli/node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:134:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.request (/Users/victorbuttner/.nvm/versions/node/v19.8.1/lib/node_modules/@we-bump/lighthouse-cli/node_modules/@cosmjs/stargate/build/queryclient/utils.js:35:30)
    at async Object.simulate (/Users/victorbuttner/.nvm/versions/node/v19.8.1/lib/node_modules/@we-bump/lighthouse-cli/node_modules/@cosmjs/stargate/build/modules/tx/queries.js:48:34)
    at async SigningCosmWasmClient.simulate (/Users/victorbuttner/.nvm/versions/node/v19.8.1/lib/node_modules/@we-bump/lighthouse-cli/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient.js:79:29)
    at async SigningCosmWasmClient.signAndBroadcast (/Users/victorbuttner/.nvm/versions/node/v19.8.1/lib/node_modules/@we-bump/lighthouse-cli/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient.js:285:35)
    at async SigningCosmWasmClient.executeMultiple (/Users/victorbuttner/.nvm/versions/node/v19.8.1/lib/node_modules/@we-bump/lighthouse-cli/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient.js:228:24)

Node.js v19.8.1

I've already the "CODE" on my testnet account :  https://www.seiscan.app/atlantic-2/accounts/sei1lkjnk4fz76a4phh7enrrxmvsv6w7946ptd89pp/codes

**Comment by md-rifatkhan** [comment]
I think the error occur for rpc url,

**Comment by tzumby** [comment]
I'm getting the same error, using `https://rpc.atlantic-2.seinetwork.io` for RPC

**Comment by md-rifatkhan** [comment]
try this, make sure you have some sei on testnet

```
{
    "mnemonic": "mnemonic",
    "rpc": "https://rpc.atlantic-2.seinetwork.io",
    "network": "atlantic-2",
    "name": "gg",
    "symbol": "gg",
    "description": "gg",
    "supply": 2222,
    "token_uri": "url",
    "royalty_percent": 5,
    "royalty_wallet": "wallet",
    "iterated_uri": false,
    "start_order": 0,
    "frozen": false,
    "hidden_metadata": false,
    "placeholder_token_uri": null,
    "groups": [
        {
            "name": "OG",
            "merkle_root": "root",
            "max_tokens": 2,
            "unit_price": 20,
            "creators": [
                {
                    "address": "address",
                    "share": 100
                }
            ],
            "start_time": "2024-01-28T07:00:00Z",
            "end_time": "2024-01-28T07:30:00Z"
        },

        {
            "name": "Whitelist",
            "merkle_root": "root",
            "max_tokens": 1,
            "unit_price": 20,
            "creators": [
                {
                    "address": "address",
                    "share": 100
                }
            ],
            "start_time": "2024-01-28T07:30:00Z",
            "end_time": "2024-01-28T08:00:00Z"
        },

        {
            "name": "Public",
            "merkle_root": null,
            "max_tokens": 1,
            "unit_price": 35,
            "creators": [
                {
                    "address": "address",
                    "share": 100
                }
            ],
            "start_time": "2024-01-28T08:00:00Z",
            "end_time": "2024-01-28T08:30:00Z"
        }
    ]
}
```

**Comment by tzumby** [comment]
I have something similar, mine didn't have the OG entry, but after I added that I get the same error. Here it is for reference:

```
{
    "rpc": "https://rpc.atlantic-2.seinetwork.io",
    "network": "atlantic-2",
    "name": "MyMint",
    "symbol": "MNT",
    "description": "Description",
    "supply": 2,
    "token_uri": "https://arweave.net/xxx",
    "royalty_percent": 0.5,
    "royalty_wallet": "sei1xxx",
    "iterated_uri": false,
    "start_order": 1,
    "frozen": false,
    "hidden_metadata": false,
    "placeholder_token_uri": null,
    "groups": [
        {
            "name": "OG",
            "merkle_root": "root",
            "max_tokens": 2,
            "unit_price": 0.05,
            "creators": [
                {
                    "address": "seixxx",
                    "share": 100
                }
            ],
            "start_time": "2024-01-28T07:00:00Z",
            "end_time": "2024-01-28T07:30:00Z"
        },
        {
            "name": "whitelist",
            "merkle_root": "0e3345a482b0b23733ca603e16a01b49c383df40f06a1edae28b681b017fae64",
            "max_tokens": 2,
            "unit_price": 0.05,
            "start_time": "2023-06-02T11:00:00Z",
            "end_time": "2024-06-03T11:50:00Z"
        },
        {
            "name": "public",
            "merkle_root": null,
            "max_tokens": 0,
            "unit_price": 1,
            "creators": [
                {
                    "address": "seixxx",
                    "share": 100
                }
            ],
            "start_time": "2024-02-01T00:11:18Z",
            "end_time": null
        }
    ],
    "mnemonic": "xxx"
}

```

**Comment by tzumby** [comment]
I also tried the OG entry with just the merkle root, same error.

**Comment by tzumby** [comment]
And I definitely have SEI in testnet wallet, I can see the funds going down every time it fails, I had 3 SEI initially and now it's down to 0.6 after many tries

**Comment by cbabbino** [comment]
Anyone ever figure this out? Same happening for me when I try to update collection

**Comment by md-rifatkhan** [comment]
Try to reinstall repo and deploy again without any changes and see if work,  just add mnemonic and rpc, 
And i see you have declared mnemonic in bottom, dont know if this causing the error.
